#Q1. What is the total revenue generated by male vs. female customers?

select gender , 
sum(purchase_amount) as total_revenue 
from custmer_behavior
group by gender;


#Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id , purchase_amount 
from custmer_behavior
where purchase_amount > (select avg(purchase_amount) from custmer_behavior ) AND discount_applied = 'Yes';


#Q3. Which are the top 5 products with the highest average review rating?

select item_purchased , round(avg(review_rating),2) avg_review_rating
from custmer_behavior
group by item_purchased
order by avg_review_rating desc 
limit 5;



#Q4. Compare the average Purchase Amounts between Standard and Express Shipping

select shipping_type , round(avg(purchase_amount),2) avg_purchase_amount
from custmer_behavior
where shipping_type = 'Standard' or shipping_type = 'Express'
group by shipping_type;



#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status , 
round(avg(purchase_amount),2) avg_purchase_amount
, sum(purchase_amount) revenue
from custmer_behavior
group by subscription_status;


#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased , 
sum(purchase_amount) revenue
from custmer_behavior
where discount_applied = 'Yes'
group by item_purchased
order by revenue desc 
limit 5;


#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and  10 then 'Returning'
    when previous_purchases > 10 then 'Loyal'
end as customer_segment,
count(*) total_cutomer
from custmer_behavior  
group by  customer_segment
order by total_cutomer desc;


#Q8. What are the top 3 most purchased products within each category?

WITH RankedProducts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        DENSE_RANK() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_num
    FROM custmer_behavior
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_purchases
FROM RankedProducts
WHERE rank_num <= 3
ORDER BY category, total_purchases DESC;



#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status , count(*) customer
from custmer_behavior
where previous_purchases > 5
group by subscription_status;


#Q10. What is the revenue contribution of each age group?

select age_group , sum(purchase_amount)
from custmer_behavior
group by age_group;
